<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

namespace GPBMetadata;

class Entity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
—"
entity.protosa.rpc.entity"
Void"
Bool
value ("
String
value (	"

StringList
values (	"
Bytes
value ("
Int64
value ("
	Int64List
values ("
Int32
value ("
	Int32List
values (""
Pager
num (
size ("Ù

TickRecord
stock_exchange (

stock_code (	

created_at (
code (	
price (
volume (
amount (
tx_dir (
tx_kind	 (
buy_order_seq
 (	
sell_order_seq (	"«
OrderRecord
stock_exchange (

stock_code (	

created_at (
code (	
price (
volume (
amount (
tx_dir (
tx_kind	 ("Þ
OrderQueueRecord
stock_exchange (

stock_code (	

created_at (

bid1_price (
bid1_quantity (

ask1_price (
ask1_quantity (
bid_volume_detail (
ask_volume_detail	 ("ï
StockQuoteRecord
stock_exchange (

stock_code (	

created_at (
status (
prev_close_price (

open_price (
latest_price (

high_price (
	low_price	 (
limit_up_price
 (
limit_down_price (
order_quantity (
volume (
amount (

bid_volume (
	bid_price (

ask_volume (
	ask_price (
bid_price_detail (
bid_volume_detail (
ask_price_detail (
ask_volume_detail ("ç
StockQuoteSnapshot
stock_symbol (	

created_at (
prev_close_price (

open_price (
latest_price (

high_price (
	low_price	 (
volume (
amount (
turnover_rate (
	amplitude (
total_stock_volume (
float_stock_volume (
total_market_capital (
float_market_capital ("K
StockQuoteSnapshotList1
values (2!.sa.rpc.entity.StockQuoteSnapshot"@
User

id (
role (
version (
comet ("B
AuthInfo

id (
role (
token (	
comet ("Þ

APIMessage

id (	
api (

created_at ("
data (2.google.protobuf.Any
code (
msg (	5
header	 (2%.sa.rpc.entity.APIMessage.HeaderEntry-
HeaderEntry
key (	
value (	:8"}
UserInfo

id (
role (
	is_enable (
name (	
passwd (	

created_at (

updated_at ("µ
Subscription
uidd (
topic (	
topic_pattern (	

is_sub_all (

expired_at (
max_subscribe_count (
used_subscribe_count (
version ("ñ
IndMISummary
stock_symbol (	

created_at (
ace_quantity_summary (
ddy_quantity_summary (
ddx_amount_summary (
ddx
 (
ddy (
ddz0 (
ddz1 (
ddz2 (
ddz3 (
ddz4 (

ddx_d5_avg (

ddy_d5_avg (
ddz0_d5_avg (
ddz1_d5_avg (
ddz2_d5_avg (
ddz3_d5_avg (
ddz4_d5_avg (
ddx_d20_avg (
ddy_d20_avg (
ddz0_d20_avg (
ddz1_d20_avg (
ddz2_d20_avg (
ddz3_d20_avg (
ddz4_d20_avg (
ddx_d60_avg (
ddy_d60_avg  (
ddz0_d60_avg! (
ddz1_d60_avg" (
ddz2_d60_avg# (
ddz3_d60_avg$ (
ddz4_d60_avg% (
ddx_d10_cont_red_count& (
ddx_d10_aggr_red_count\' ("?
IndMISummaryList+
values (2.sa.rpc.entity.IndMISummary"ñ
IndDDSummary
stock_symbol (	

created_at (
ace_quantity_summary (
ddy_quantity_summary (
ddx_amount_summary (
ddx
 (
ddy (
ddz0 (
ddz1 (
ddz2 (
ddz3 (
ddz4 (

ddx_d5_avg (

ddy_d5_avg (
ddz0_d5_avg (
ddz1_d5_avg (
ddz2_d5_avg (
ddz3_d5_avg (
ddz4_d5_avg (
ddx_d20_avg (
ddy_d20_avg (
ddz0_d20_avg (
ddz1_d20_avg (
ddz2_d20_avg (
ddz3_d20_avg (
ddz4_d20_avg (
ddx_d60_avg (
ddy_d60_avg  (
ddz0_d60_avg! (
ddz1_d60_avg" (
ddz2_d60_avg# (
ddz3_d60_avg$ (
ddz4_d60_avg% (
ddx_d10_cont_red_count& (
ddx_d10_aggr_red_count\' ("?
IndDDSummaryList+
values (2.sa.rpc.entity.IndDDSummary"`
GetStockQuoteSnapShotReq
stock_symbol (	
min_created_at (
max_created_at ("^
	GetIndReq
ind (
stock_symbol (	
min_created_at (
max_created_at (BZsa-common/rpc/entitybproto3'
        , true);

        static::$is_initialized = true;
    }
}

