<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

namespace Sa\Rpc\Entity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *股票行情快照
 *
 * Generated from protobuf message <code>sa.rpc.entity.StockQuoteSnapshot</code>
 */
class StockQuoteSnapshot extends \Google\Protobuf\Internal\Message
{
    /**
     *证券标识
     *
     * Generated from protobuf field <code>string stock_symbol = 1;</code>
     */
    protected $stock_symbol = '';
    /**
     *uint32 stock_exchange = 1;//证券市场，见数据字典
     *string stock_code = 2;//证券代码
     *string stock_name = 3;//证券名称，暂不启用，可能无
     *
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     */
    protected $created_at = 0;
    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     */
    protected $prev_close_price = 0;
    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     */
    protected $open_price = 0;
    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     */
    protected $latest_price = 0;
    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     */
    protected $high_price = 0;
    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     */
    protected $low_price = 0;
    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     */
    protected $volume = 0;
    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     */
    protected $amount = 0;
    /**
     *换手率(百分比)
     *
     * Generated from protobuf field <code>float turnover_rate = 15;</code>
     */
    protected $turnover_rate = 0.0;
    /**
     *振幅(百分比)
     *
     * Generated from protobuf field <code>float amplitude = 16;</code>
     */
    protected $amplitude = 0.0;
    /**
     *总股本
     *
     * Generated from protobuf field <code>uint64 total_stock_volume = 17;</code>
     */
    protected $total_stock_volume = 0;
    /**
     *流通股
     *
     * Generated from protobuf field <code>uint64 float_stock_volume = 18;</code>
     */
    protected $float_stock_volume = 0;
    /**
     *总市值
     *
     * Generated from protobuf field <code>uint64 total_market_capital = 19;</code>
     */
    protected $total_market_capital = 0;
    /**
     *流通市值
     *
     * Generated from protobuf field <code>uint64 float_market_capital = 20;</code>
     */
    protected $float_market_capital = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stock_symbol
     *          证券标识
     *     @type int|string $created_at
     *          uint32 stock_exchange = 1;//证券市场，见数据字典
     *          string stock_code = 2;//证券代码
     *          string stock_name = 3;//证券名称，暂不启用，可能无
     *     @type int $prev_close_price
     *          前收盘价
     *     @type int $open_price
     *          开盘价
     *     @type int $latest_price
     *          最新价
     *     @type int $high_price
     *          最高价
     *     @type int $low_price
     *          最低价
     *     @type int|string $volume
     *          成交数量
     *     @type int|string $amount
     *          成交金额
     *     @type float $turnover_rate
     *          换手率(百分比)
     *     @type float $amplitude
     *          振幅(百分比)
     *     @type int|string $total_stock_volume
     *          总股本
     *     @type int|string $float_stock_volume
     *          流通股
     *     @type int|string $total_market_capital
     *          总市值
     *     @type int|string $float_market_capital
     *          流通市值
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Entity::initOnce();
        parent::__construct($data);
    }

    /**
     *证券标识
     *
     * Generated from protobuf field <code>string stock_symbol = 1;</code>
     * @return string
     */
    public function getStockSymbol()
    {
        return $this->stock_symbol;
    }

    /**
     *证券标识
     *
     * Generated from protobuf field <code>string stock_symbol = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStockSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_symbol = $var;

        return $this;
    }

    /**
     *uint32 stock_exchange = 1;//证券市场，见数据字典
     *string stock_code = 2;//证券代码
     *string stock_name = 3;//证券名称，暂不启用，可能无
     *
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     *uint32 stock_exchange = 1;//证券市场，见数据字典
     *string stock_code = 2;//证券代码
     *string stock_name = 3;//证券名称，暂不启用，可能无
     *
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     * @return int
     */
    public function getPrevClosePrice()
    {
        return $this->prev_close_price;
    }

    /**
     *前收盘价
     *
     * Generated from protobuf field <code>uint32 prev_close_price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrevClosePrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->prev_close_price = $var;

        return $this;
    }

    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     * @return int
     */
    public function getOpenPrice()
    {
        return $this->open_price;
    }

    /**
     *开盘价
     *
     * Generated from protobuf field <code>uint32 open_price = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOpenPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->open_price = $var;

        return $this;
    }

    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     * @return int
     */
    public function getLatestPrice()
    {
        return $this->latest_price;
    }

    /**
     *最新价
     *
     * Generated from protobuf field <code>uint32 latest_price = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLatestPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->latest_price = $var;

        return $this;
    }

    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     * @return int
     */
    public function getHighPrice()
    {
        return $this->high_price;
    }

    /**
     *最高价
     *
     * Generated from protobuf field <code>uint32 high_price = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setHighPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->high_price = $var;

        return $this;
    }

    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     * @return int
     */
    public function getLowPrice()
    {
        return $this->low_price;
    }

    /**
     *最低价
     *
     * Generated from protobuf field <code>uint32 low_price = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLowPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->low_price = $var;

        return $this;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     *成交数量
     *
     * Generated from protobuf field <code>uint64 volume = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *成交金额
     *
     * Generated from protobuf field <code>uint64 amount = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *换手率(百分比)
     *
     * Generated from protobuf field <code>float turnover_rate = 15;</code>
     * @return float
     */
    public function getTurnoverRate()
    {
        return $this->turnover_rate;
    }

    /**
     *换手率(百分比)
     *
     * Generated from protobuf field <code>float turnover_rate = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setTurnoverRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->turnover_rate = $var;

        return $this;
    }

    /**
     *振幅(百分比)
     *
     * Generated from protobuf field <code>float amplitude = 16;</code>
     * @return float
     */
    public function getAmplitude()
    {
        return $this->amplitude;
    }

    /**
     *振幅(百分比)
     *
     * Generated from protobuf field <code>float amplitude = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setAmplitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->amplitude = $var;

        return $this;
    }

    /**
     *总股本
     *
     * Generated from protobuf field <code>uint64 total_stock_volume = 17;</code>
     * @return int|string
     */
    public function getTotalStockVolume()
    {
        return $this->total_stock_volume;
    }

    /**
     *总股本
     *
     * Generated from protobuf field <code>uint64 total_stock_volume = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalStockVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->total_stock_volume = $var;

        return $this;
    }

    /**
     *流通股
     *
     * Generated from protobuf field <code>uint64 float_stock_volume = 18;</code>
     * @return int|string
     */
    public function getFloatStockVolume()
    {
        return $this->float_stock_volume;
    }

    /**
     *流通股
     *
     * Generated from protobuf field <code>uint64 float_stock_volume = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFloatStockVolume($var)
    {
        GPBUtil::checkUint64($var);
        $this->float_stock_volume = $var;

        return $this;
    }

    /**
     *总市值
     *
     * Generated from protobuf field <code>uint64 total_market_capital = 19;</code>
     * @return int|string
     */
    public function getTotalMarketCapital()
    {
        return $this->total_market_capital;
    }

    /**
     *总市值
     *
     * Generated from protobuf field <code>uint64 total_market_capital = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalMarketCapital($var)
    {
        GPBUtil::checkUint64($var);
        $this->total_market_capital = $var;

        return $this;
    }

    /**
     *流通市值
     *
     * Generated from protobuf field <code>uint64 float_market_capital = 20;</code>
     * @return int|string
     */
    public function getFloatMarketCapital()
    {
        return $this->float_market_capital;
    }

    /**
     *流通市值
     *
     * Generated from protobuf field <code>uint64 float_market_capital = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFloatMarketCapital($var)
    {
        GPBUtil::checkUint64($var);
        $this->float_market_capital = $var;

        return $this;
    }

}

