Address = 'localhost:8090'#代理服务器监听地址
RpcServer = 'localhost:37011'#RPC接口行情服务器地址
TcpServer = 'localhost:37001'#TCP接口行情服务器地址
User = '1.1'#用户角色.用户ID
Passwd = 'xx'#用户密钥
TxMsgCacheSize = 1000#行情推送消息缓存数，默认1000
DataDir = './data'#数据目录，默认./data
EnableWriteTxMsgToFile = false#是否将行情推送消息保存到文件
EnableWriteTxMsgAsJson = false#是否将行情推送消息转换为json